Creado
wolox-training/jc-net-core pull request #10
Opened 2019-05-23 18:29 UTC by Casanova569

Summary:
Add the function of create a movie to the application.
Objetive: The trello card is considered approved if a movie can be created.

Trello Card:
Name: Creado
Link: https://trello.com/c/8T2W21tu/8-creado

2019-05-23 20:35 UTC, mikolaslorant commented
Pull request titles should be in english :)

2019-05-27 16:03 UTC, mikolaslorant requested changes

2019-05-27 16:03 UTC, mikolaslorant commented on src/Views/MovieApp/Create.cshtml
> +</div>
add eof

2019-05-27 16:03 UTC, mikolaslorant commented on src/Repositories/DataBase/MvcMovieContext.cs
>  }
Add EOF

2019-05-27 16:03 UTC, mikolaslorant commented on src/Repositories/DataBase/MvcMovieContext.cs
> +        public MvcMovieContext (DbContextOptions<MvcMovieContext> options): base(options){}
add space after base(options)

2019-05-29 14:06 UTC, truccomarcos requested changes

2019-05-29 14:06 UTC, truccomarcos commented on src/Controllers/MovieApp.cs
> +    public class MovieAppController : Controller
Class and file names should match. Update the file name to match the class name

2019-05-29 14:06 UTC, truccomarcos commented on src/Controllers/MovieApp.cs
> +        }
Add a blank line here to separate the index method from the property. Also, add the [HttpGet] tag to it

2019-05-29 14:06 UTC, truccomarcos commented on src/Controllers/MovieApp.cs
> +}
Add empty line at EOF

2019-05-29 14:06 UTC, truccomarcos commented on src/Controllers/MovieApp.cs
> +        }
Add empty line

2019-05-29 14:06 UTC, truccomarcos commented on src/Controllers/MovieApp.cs
> +        }
We usually put properties like this one below the Endpoints (in this case, after the POST Create)

2019-05-29 14:06 UTC, truccomarcos commented on src/Controllers/MovieApp.cs
> +            return View();
Try redirecting the user to the index page for this controller (even though the list is not ready yet, the view is there

2019-06-05 13:47 UTC, mikolaslorant requested changes

2019-06-05 13:47 UTC, mikolaslorant commented on src/Controllers/MovieAppController.cs
> +        public IActionResult Create([Bind("ID,Title,ReleaseDate,Genre,Price")] Movie movie)
As I pointed out int other prs. Don't use bind and make the method receive a MovieViewModel. This allows for independence between the view and the database model. Also It's  a good practice to remove  The binding is resolved automatically by the framework.

2019-06-05 13:47 UTC, mikolaslorant commented on src/Controllers/MovieAppController.cs
> +            UnitOfWork.Movies.Add(movie);
Also before adding the movie you could add a check of the model to see if its valid

2019-06-05 17:19 UTC, truccomarcos approved these changes

2019-06-05 17:33 UTC, merged