List of movies
wolox-training/jc-net-core pull request #11
Opened 2019-05-24 16:31 UTC by Casanova569

Summary:
The trello card is considered approved if it is returned (is viewed) a list of Movies from a VM.

Trello Card:
Name: Lista de películas
Link: https://trello.com/c/JFReK4ST/28-lista-de-pel%C3%ADculas

2019-05-29 14:11 UTC, truccomarcos requested changes

2019-05-29 14:11 UTC, truccomarcos commented on src/Views/MovieApp/Index.cshtml
> +<p>
Is it necessary to have a `<p>` tag here? What does it do?

2019-05-29 14:11 UTC, truccomarcos commented on src/Controllers/MovieApp.cs
> +            return RedirectPermanent("/MovieApp");
Try using RedirectToAction instead of RedirectPermanent

2019-06-05 13:50 UTC, mikolaslorant requested changes

2019-06-05 13:50 UTC, mikolaslorant commented on src/Controllers/MovieAppController.cs
> +            return View(UnitOfWork.Movies.GetAll());
As I pointed out in the Create pr you could return a MovieViewModel instead of the actual object. Generally not all information of the model is needed in the view

2019-06-05 16:43 UTC, Casanova569 commented on src/Controllers/MovieAppController.cs
> +            return View(UnitOfWork.Movies.GetAll());
I fixed that in the search (card/branch).

2019-06-05 17:23 UTC, truccomarcos approved these changes
Everything seems to be alright. After you solve the merge conflicts, let me know before you merge so I can take a quick look

2019-06-06 13:47 UTC, merged