edit finish
wolox-training/jc-net-core pull request #12
Opened 2019-05-24 17:56 UTC by Casanova569

Summary:
The trello card is approved if you can edit a movie.

Trello Card:
Name: Edición
Link: https://trello.com/c/CJEjr6iZ/7-edici%C3%B3n

2019-05-30 15:19 UTC, truccomarcos requested changes

2019-05-30 15:19 UTC, truccomarcos commented on src/Views/MovieApp/Edit.cshtml
> +@model MvcMovie.Models.Movie
Try using a partial view for this form

2019-05-30 15:19 UTC, truccomarcos commented on src/Controllers/MovieApp.cs
> +            return RedirectToAction("Index");
This wioll always redirect to the index view, even if the movie creation fails

2019-06-01 14:12 UTC, mikolaslorant requested changes

2019-06-01 14:12 UTC, mikolaslorant commented on src/Controllers/MovieApp.cs
> +        public IActionResult Edit(int id, [Bind("Id,Title,ReleaseDate,Genre,Price")] Movie movie)
You could try creating a MovieViewModel with the attributes you need to edit.
public IActionResult Edit(int id, MovieViewModel movie)
this is bettter in two ways:
A bind is not necessary, parameter attributes will be automatically matched with the viewmodel.
And Sometimes you need independece between the frontend validation and the database. For example you may want to restrict the ammount of characters a method receives as a parameter (this could be done with a data annotation in the view model) but you may want to allow for longer registers in your database.

2019-06-01 14:12 UTC, mikolaslorant commented on src/Views/Shared/_Create-Edit-Movie.cshtml
> +    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
remove extra space to the left of the cshtml

2019-06-05 17:37 UTC, truccomarcos requested changes

2019-06-05 17:37 UTC, truccomarcos commented on src/Views/Shared/Create-Edit-Movie.cshtml
> +@model MvcMovie.Models.MovieViewModel
The standard for partial views is to have them start with an underscore. I'd rename this to `_Form.cshtml`

2019-06-05 17:37 UTC, truccomarcos commented on src/Views/Shared/Create-Edit-Movie.cshtml
> +@model MvcMovie.Models.MovieViewModel
Also, you should be able to move this file to the MovieApp views folder

2019-06-06 13:44 UTC, Casanova569 commented on src/Views/Shared/Create-Edit-Movie.cshtml
> +@model MvcMovie.Models.MovieViewModel
I fixed that in authentication (pr).

2019-06-07 11:59 UTC, truccomarcos commented
@Casanova569 Don't forget to reassing this PR once you've made changes

2019-06-07 12:00 UTC, truccomarcos submitted a review, later dismissed

2019-06-07 12:05 UTC, truccomarcos requested changes
There is no Edit endpoint. How can you access the view?

2019-06-07 12:09 UTC, truccomarcos commented on src/Views/Shared/Create-Edit-Movie.cshtml
> +@model MvcMovie.Models.MovieViewModel
Don't forget to make the changes on the PR they are marked on

2019-06-07 12:43 UTC, truccomarcos requested changes
When testing this, I was able to add a negative price. Try updating the model data annotations

2019-06-07 12:56 UTC, Casanova569 commented
Yes, I did that in the pr of validation.

2019-06-10 15:03 UTC, truccomarcos approved these changes

2019-06-10 16:03 UTC, merged