Details and Delete
wolox-training/jc-net-core pull request #13
Opened 2019-05-24 18:43 UTC by Casanova569

Summary:
The trello card is considered approved if you can access for more detail and delete a movie.

Trello Card:
Name: Detalle y Borrado
Link: https://trello.com/c/JtQ6dbxg/9-detalle-y-borrado

2019-05-29 12:38 UTC, mikolaslorant requested changes

2019-05-29 12:38 UTC, mikolaslorant commented on src/Controllers/MovieApp.cs
> +            return RedirectPermanent("/MovieApp");
Use RedirectToAction instead.

2019-05-29 12:38 UTC, mikolaslorant commented on src/Controllers/MovieApp.cs
> +            else if (ModelState.IsValid)
maybe ask if (!ModelState.IsValid) and return an error.

2019-05-29 12:38 UTC, mikolaslorant commented on src/Repositories/Repository.cs
>  }
add Eof

2019-05-30 15:32 UTC, truccomarcos requested changes

2019-05-30 15:32 UTC, truccomarcos commented on src/Controllers/MovieApp.cs
> +                return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
Watch out here, you are removing the movie id check. you should probably check if the movie exists before getting it. what happens if a non existent id is sent?

2019-05-30 15:32 UTC, truccomarcos commented on src/Views/MovieApp/Delete.cshtml
> +    <h1>Are you sure?</h1>
Use the localizer for this string

2019-05-30 15:32 UTC, truccomarcos commented on src/Views/MovieApp/Details.cshtml
> +@if (Model != null)
Should we be able to get to this view if the model was null?

2019-06-11 12:42 UTC, truccomarcos requested changes

2019-06-11 12:42 UTC, truccomarcos commented on src/Controllers/MovieAppController.cs
> +        public IActionResult DeleteConfirmed(int id, bool notUsed)
what is `bool notUsed` for?

2019-06-11 12:42 UTC, truccomarcos commented on src/Views/MovieApp/Delete.cshtml
> +    <h1>@ViewData["Question"]</h1>
Does this show the movie being deleted?

2019-06-11 14:54 UTC, truccomarcos approved these changes

2019-06-11 15:05 UTC, merged