Search
wolox-training/jc-net-core pull request #15
Opened 2019-05-28 15:11 UTC by Casanova569

Summary:
The trello card is considered approved when the user can search and filter movies.

Trello Card:
Name: Búsqueda y Filtrado
Link: https://trello.com/c/NGsSwQOo/10-b%C3%BAsqueda-y-filtrado

2019-06-05 20:10 UTC, truccomarcos requested changes

2019-06-05 20:10 UTC, truccomarcos commented on src/Controllers/MovieAppController.cs
> +
Remove empty line

2019-06-05 20:10 UTC, truccomarcos commented on src/Controllers/MovieAppController.cs
> +
Same here (empty line)

2019-06-05 20:10 UTC, truccomarcos commented on src/Controllers/MovieAppController.cs
> +            if (!string.IsNullOrEmpty(searchString))
When we have a one line `if` block. we usually write them without the brackets.
```chsarp
if (!string.IsNullOrEmpty(searchString))
    movies = movies.Where(s => s.Title.Contains(searchString));
```

2019-06-05 20:10 UTC, truccomarcos commented on src/Controllers/MovieAppController.cs
> +            if (!string.IsNullOrEmpty(movieGenre))
Same here (one line `if` blocvk)

2019-06-05 20:10 UTC, truccomarcos commented on src/Controllers/MovieAppController.cs
> +
Same here (empty line)

2019-06-05 20:10 UTC, truccomarcos commented on src/Controllers/MovieAppController.cs
> +            return "From [HttpPost]Index: filter on " + searchString;
What is this method for?

2019-06-05 20:10 UTC, truccomarcos commented on src/Repositories/Interfaces/IMovieRepository.cs
> +        IEnumerable<Movie> GetMovieWithGenre(string genre);
This methods are not being used, we should probably remove them if they have no references

2019-06-05 20:10 UTC, truccomarcos commented on src/Repositories/MovieRepository.cs
> +        public IEnumerable<Movie> GetMovieWithGenre(string genre)
Same here (Remove unused methods).
Also, try to keep al methods on the top and properties at the bottom of the class.

2019-06-05 20:10 UTC, truccomarcos commented on src/Views/MovieApp/Index.cshtml
> +@if (Model !=null)
You should probably also check if the `Movies` attribute of the view model has any elements (Model.Movies.Any())

2019-06-10 16:06 UTC, truccomarcos requested changes
When I filter by one genre, and try to filter by another one, I get only a dropdown for the first genre. Try filtering by one genre and then filtering by another one to see the error

2019-06-10 18:39 UTC, Casanova569 commented on src/Views/MovieApp/Index.cshtml
> +@if (Model !=null)
I fixed the errors in the pr commentAjax.

2019-06-11 14:46 UTC, truccomarcos approved these changes

2019-06-11 16:24 UTC, merged