rating
wolox-training/jc-net-core pull request #16
Opened 2019-05-28 18:40 UTC by Casanova569

Summary:
The trello card is considered approved when the new property (rating) is added to the movie.

Trello Card:
Name: Nueva propiedad en película
Link: https://trello.com/c/T1K6184C/11-nueva-propiedad-en-pel%C3%ADcula

2019-05-29 12:30 UTC, mikolaslorant requested changes

2019-05-29 12:30 UTC, mikolaslorant commented on src/Views/MovieApp/Index.cshtml
> +                @Html.DisplayNameFor(model => model.Movies[0].Rating)
I believe this could throw a null pointer exception if no movies are passed to the view

2019-06-01 14:03 UTC, mikolaslorant requested changes

2019-06-01 14:03 UTC, mikolaslorant commented on src/Controllers/MovieApp.cs
> +        public IActionResult Edit(int id, [Bind("Id,Title,ReleaseDate,Genre,Price,Rating")] Movie movie)
You could try creating a MovieViewModel with the attributes you need to edit. 
public IActionResult Edit(int id, MovieViewModel movie)
this is bettter in two ways:
A bind is not necessary, parameter attributes will be automatically matched with the viewmodel.
And Sometimes you need independece between the frontend validation and the database. For example you may want to restrict the ammount of characters a method receives as a parameter (this could be done with a data annotation in the view model) but you may want to allow for longer registers in your database.

2019-06-11 14:49 UTC, truccomarcos requested changes

2019-06-11 14:49 UTC, truccomarcos commented on src/Models/MovieViewModel.cs
> +<<<<<<< HEAD
Merge conflicts :P

2019-06-11 16:23 UTC, truccomarcos approved these changes

2019-06-11 16:27 UTC, merged