Order (sorter)
wolox-training/jc-net-core pull request #18
Opened 2019-05-31 16:40 UTC by Casanova569

Summary:
The trello card is considered approved if the user can order the list of movies.

Trello Card:
Name: Orden
Link: https://trello.com/c/IumokATt/13-orden

2019-06-01 14:08 UTC, mikolaslorant requested changes

2019-06-01 14:08 UTC, mikolaslorant commented on src/Controllers/MovieApp.cs
> +
you could add a ThenOrderBy clause with Title (or Id). So if ordered by price and all of them have the same price, the movies are at least mantain some type of order.

2019-06-10 15:10 UTC, truccomarcos requested changes

2019-06-10 15:10 UTC, truccomarcos commented on src/Models/MovieViewModel.cs
> +<<<<<<< HEAD
Watch out for the conflicts here

2019-06-11 17:53 UTC, truccomarcos requested changes

2019-06-11 17:53 UTC, truccomarcos commented on src/Models/MovieViewModel.cs
> +	public class MovieViewModel
Watch out for identation here

2019-06-11 19:04 UTC, truccomarcos approved these changes

2019-06-11 19:05 UTC, merged