kick off
wolox-training/jc-net-core pull request #2
Opened 2019-05-20 16:43 UTC by Casanova569

Summary:
This is the first steps in the process to create a netcore proyect.
Objetive: The trello card is considered approved if the default environment can be lifted on the localhost.

Trello card:
Name: Kick-Off
Link: https://trello.com/c/7BCYh54j/1-kick-off

2019-05-20 18:44 UTC, truccomarcos requested changes

2019-05-20 18:44 UTC, truccomarcos commented on .vscode/launch.json
> +{
Don't forget to add this folder to `.gitignore` (look up how to untrack specific files that have been added to the repository)

2019-05-20 18:44 UTC, truccomarcos commented on .gitignore
> +obj
Add an empty line at the end of the file (git doesn't like it when files don't end on a blank line :P )
![image](https://user-images.githubusercontent.com/16925524/58044390-01ba6300-7b16-11e9-8ca4-6e4bda939636.png)

2019-05-22 13:03 UTC, Casanova569 commented on .vscode/launch.json
> +{
I fixed the error in the next branch - MVC (controller).

2019-05-22 13:04 UTC, Casanova569 commented on .gitignore
> +obj
I fixed the error in the next branch - MVC (controller).

2019-05-22 13:25 UTC, truccomarcos approved these changes

2019-05-22 13:28 UTC, mikolaslorant approved these changes

2019-05-23 14:26 UTC, merged