Comment
wolox-training/jc-net-core pull request #22
Opened 2019-06-04 19:27 UTC by Casanova569

Summary:
The trello cards are considered approved when the movie comment "model" is linked correctly and had a  "view" (for the comments).

Trello Card:
Name: Comentarios en modelo de película
Link: https://trello.com/c/snUit3kz/15-comentarios-en-modelo-de-pel%C3%ADcula
Name: Vista de comentarios en película
Link: https://trello.com/c/Z0lZLIwT/16-vista-de-comentarios-en-pel%C3%ADcula

2019-06-11 15:50 UTC, truccomarcos requested changes

2019-06-11 15:50 UTC, truccomarcos commented on src/Controllers/MovieAppController.cs
> +		public IActionResult Comment(int id)
Fix identation

2019-06-11 15:50 UTC, truccomarcos commented on src/Controllers/MovieAppController.cs
> +            commentVM.movie=movie;
add spaces before and after the `=`

2019-06-11 15:50 UTC, truccomarcos commented on src/Controllers/MovieAppController.cs
> +            commentVM.movie=movie;
Try setting the movie and comments using the commentViewModel constructor

2019-06-11 15:50 UTC, truccomarcos commented on src/Controllers/MovieAppController.cs
> +            var comment = UnitOfWork.Comments.GetAll();
There's no need to get comments like this. You should be able to get them from the movie entity (`Movie.Comments`). Look up for loading related data on EF Core.

2019-06-11 15:50 UTC, truccomarcos commented on src/Controllers/MovieAppController.cs
> +		    return View(commentVM);
Fixed identation

2019-06-11 15:50 UTC, truccomarcos commented on src/Controllers/MovieAppController.cs
> +                comment.MovieID = id;
What happens if the movie id is not a reference for an existing movie? Try to get the movie and add the comment using the `Comment` collection in the `Movie` entity

2019-06-11 15:50 UTC, truccomarcos commented on src/Models/Comment.cs
> +        public int CommentId { get; set; }
This is the `Comment` class, so we should just call this attribute `Id`

2019-06-11 15:50 UTC, truccomarcos commented on src/Models/Comment.cs
> +        public DateTime ReleaseDate { get; set; }
What is the release date for? isn't the release date a movie entity?

2019-06-11 15:50 UTC, truccomarcos commented on src/Models/Comment.cs
> +        public int MovieID { get; set; }
`MovieId`. Should probably be required

2019-06-11 15:50 UTC, truccomarcos commented on src/Models/Comment.cs
> +        public Movie Movie { get; set; }
make this a virtual property
public virtual Movie Movie { get; set; }

2019-06-11 15:50 UTC, truccomarcos commented on src/Models/CommentViewModel.cs
> +using System;
Remember that we use view model entities to avoid referencing model classes from the database.

Remove all attributes that don't match the `Comment` model

2019-06-11 15:50 UTC, truccomarcos commented on src/Models/Movie.cs
> +        public ICollection<Comment> Comment { get; set; }
This is a collection, so we should be calling it as a plural (`Comments`)
also, make it a virtual attribute

2019-06-11 15:50 UTC, truccomarcos commented on src/Models/MovieViewModel.cs
> +        public ICollection<Comment> Comment { get; set; }
Remember we are using view models to avoid accesing the model classes. Try making this a `CommentViewModel` collection

2019-06-11 15:50 UTC, truccomarcos commented on src/Repositories/DataBase/MvcMovieContext.cs
> +        public DbSet<Comment> Comment { get; set; }
Comments

2019-06-14 15:36 UTC, Casanova569 commented on src/Models/CommentViewModel.cs
> +using System;
Fixed that in commentAjax (pr)

2019-06-18 15:29 UTC, truccomarcos commented on src/Controllers/MovieAppController.cs
> +                comment.MovieID = id;
@Casanova569

2019-06-19 15:15 UTC, truccomarcos approved these changes

2019-06-19 15:23 UTC, merged