Comment AJAX
wolox-training/jc-net-core pull request #24
Opened 2019-06-10 14:57 UTC by Casanova569

Summary:
The trello card is considered approved if a detail (add comment) can be modified from the view using AJAX.

Trello Card:
Name: Ajax para comentarios
Link: https://trello.com/c/asX0WmRw/29-ajax-para-comentarios

2019-06-11 15:53 UTC, truccomarcos requested changes

2019-06-11 15:53 UTC, truccomarcos commented on src/Controllers/api/v1/MovieApiController.cs
> +	[Route("api/v1/MovieApiController")]
Fix identation

2019-06-11 15:53 UTC, truccomarcos commented on src/Controllers/api/v1/MovieApiController.cs
> +			Comment comment = new Comment();
Try creating a comment constructor that receives a view model

2019-06-11 15:53 UTC, truccomarcos commented on src/Controllers/api/v1/MovieApiController.cs
> +            return ("Se agrego con éxito");
This should return an okay status code. Try returning `Ok(message)`

2019-06-11 15:53 UTC, truccomarcos commented on src/wwwroot/js/site.js
> +            tableBody.append('<tr> <td>' + comment.Title + '</td>' + '<td>' + comment.Content + '</td>' + '<td>' + dataC + '</td> <tr>');
You are appending the body before you have confirmation that it was added to the database. Try appending it when the ajax is successful

2019-06-19 15:20 UTC, truccomarcos requested changes

2019-06-19 15:20 UTC, truccomarcos commented on src/Controllers/MovieAppController.cs
> +            var comments = UnitOfWork.Comments.GetAll();
Why are you getting the comments here?

2019-06-19 15:21 UTC, truccomarcos commented
Try adding a validation on the js code, so that an error is shown if the comment is empty

2019-06-19 15:46 UTC, mikolaslorant requested changes

2019-06-19 15:46 UTC, mikolaslorant commented on src/Controllers/MovieAppController.cs
> +            return View(movieVM);
these two lines could be written as one return new View(new MovieViewModel(movie));

2019-06-19 15:46 UTC, mikolaslorant commented on src/Controllers/api/v1/MovieApiController.cs
> +            return ("Ok");
Use Ok() function

2019-06-19 15:46 UTC, mikolaslorant commented on src/Controllers/api/v1/MovieApiController.cs
> +            UnitOfWork.Comments.Update(comment);
Why an  update and not an add?

2019-06-19 15:46 UTC, mikolaslorant commented on src/Models/Comment.cs
>          public Comment(){ }
add a space after comment()

2019-06-19 15:46 UTC, mikolaslorant commented on src/Views/MovieApp/Index.cshtml
> +<form asp-controller=" asp-action="Index" method="get">
something went wrong here after the asp-controller.

2019-06-19 15:46 UTC, mikolaslorant commented on src/src.csproj
> +</Project>
add eof

2019-06-19 15:46 UTC, mikolaslorant commented on src/Controllers/api/v1/MovieApiController.cs
>          {
put these curly brackets in the upper liner

2019-06-21 19:19 UTC, truccomarcos approved these changes

2019-06-21 19:23 UTC, merged