MVC
wolox-training/jc-net-core pull request #5
Opened 2019-05-21 13:47 UTC by Casanova569

Summary:
Objetive: Complete the first steps in the creation of the MVC application.

Controller: The trello card is considered approved, if you can access the controller path and see the phrase that returns (message).
View: The trello card is considered approved, if the controller returns a view instead of the previous card's string (controller card).
Model: The trello card is considered approved, if it completes the configuration of the Database and if the Movie Model was generated.

Trello Cards:

Name: MVC - Controllers
Link: https://trello.com/c/KzY22vCG/2-mvc-controllers

Name: MVC - Views
Link: https://trello.com/c/WpPl3iKb/3-mvc-views

Name: MVC - Models
Link: https://trello.com/c/aKwxQCg0/4-mvc-models

2019-05-22 13:22 UTC, mikolaslorant commented
I suggest reading on Syleing pull request descriptions for exmaple:
Adding ## to mark titles

2019-05-22 13:24 UTC, mikolaslorant requested changes

2019-05-22 13:24 UTC, mikolaslorant commented on src/Controllers/HelloWorld.cs
> +        //
remove comments

2019-05-22 13:24 UTC, mikolaslorant commented on src/Controllers/HelloWorld.cs
> +}
Add blank line at end of file (EOF)

2019-05-22 13:24 UTC, mikolaslorant commented on src/Startup.cs
> +            //services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
remove comments

2019-05-22 13:24 UTC, mikolaslorant commented on src/src.csproj
> +
remove blank lines

2019-05-22 13:54 UTC, truccomarcos commented on .gitignore
> +.vscode
The .vscode folder is still on the branch even though we added it to the `.gitignore` file. Try using the method on [here](http://www.codeblocq.com/2016/01/Untrack-files-already-added-to-git-repository-based-on-gitignore) to remove them (watch out on Step 2, there's no need to remove all files, only the `.vscode` folder)

2019-05-23 14:31 UTC, truccomarcos commented on src/src.csproj
> +    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.2.0"/>
This package will not be used on this feature (it's just necessary for the migrations). Make sure you remove it from this branch

2019-05-23 14:53 UTC, truccomarcos requested changes

2019-05-23 14:53 UTC, truccomarcos commented on src/Controllers/HelloWorld.cs
> +    // GET: /HelloWorld/
Remove this comments

2019-05-23 16:04 UTC, truccomarcos requested changes

2019-05-23 16:04 UTC, truccomarcos commented on src/Startup.cs
> +
Same as mentioned above.

2019-05-23 16:04 UTC, truccomarcos commented on src/Controllers/HelloWorld.cs
> +
As a convention, we try to remove empty lines after a `{`. Also, watch out the indentation for the methods.

2019-05-23 16:04 UTC, truccomarcos commented on src/Startup.cs
> +using System.Globalization;
We have a convention for how we sort packages. We sort them alphabetically, but we put System packages first. In this case, you should have 
```csharp
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using MvcMovie.Models;
using MvcMovie.Repositories.Database;
```

2019-05-23 16:04 UTC, truccomarcos commented on src/Startup.cs
> +using System.Globalization;
Also, if you select all the usings and click on the 💡, vscode might prompt you to remove unnecesary usings (EFCore might be taken away on this PR)

2019-05-27 12:10 UTC, truccomarcos commented on src/Startup.cs
> +﻿// src/Repositories/Database/Startup.cs
Remove this comment

2019-05-27 12:10 UTC, truccomarcos commented on src/Startup.cs
> +using src.Models;
Why is this using necessary?

2019-05-27 16:12 UTC, truccomarcos approved these changes

2019-05-27 16:26 UTC, merged