Mvc models
wolox-training/jc-net-core pull request #8
Opened 2019-05-22 12:39 UTC by Casanova569

2019-05-22 13:14 UTC, mikolaslorant requested changes

2019-05-22 13:14 UTC, mikolaslorant commented on src/Models/MvcMovieContext.cs
> +}
Add EOF (end of file blank line)

2019-05-22 13:14 UTC, mikolaslorant commented on src/Startup.cs
> +            //services.AddMvc();
remove comments

2019-05-22 13:14 UTC, mikolaslorant commented on src/Models/MvcMovieContext.cs
> +        public MvcMovieContext (DbContextOptions<MvcMovieContext> options)
when a method is empty try to write everything in same line. Eg.:
public DatabaseContext (DbContextOptions<DatabaseContext> options) {}

2019-05-22 13:14 UTC, mikolaslorant commented on src/appsettings.Development.json
> -  }
Add appsettings.Development.json to your .gitignore file. Your development json should be private and not shared with the team using the repository.

2019-05-22 13:14 UTC, mikolaslorant commented on src/appsettings.Development.json
> +  "ConnectionString": "User ID=dev;Password=dev;Host=localhost;Port=5432;Database=MvcMovie.db;Pooling=true;Timeout=1024;CommandTimeout=1024;"
Eg.: this connection String is particular to your local configuration

2019-05-22 13:14 UTC, mikolaslorant commented on src/Models/MvcMovieContext.cs
> +    public class MvcMovieContext : DbContext
Although MvcMovie corresponds with the name of the application I suggest using a more generic name like DatabaseContext for the class. (just a suggestion)

2019-05-23 13:57 UTC, mikolaslorant requested changes

2019-05-23 13:57 UTC, mikolaslorant commented on src/appsettings.Development.json
> -  }
remove this file from your pull request and set it in your .gitignore

2019-05-23 13:59 UTC, mikolaslorant requested changes

2019-05-23 13:59 UTC, mikolaslorant commented on src/Models/MvcMovieContext.cs
> +        public DbSet<MvcMovie.Models.Movie> Movie { get; set; }
add using at the top of file to import models and make Movie plural like so:
public DbSet<Movie> Movies { get; set; }

2019-05-23 13:59 UTC, mikolaslorant commented on src/Models/MvcMovieContext.cs
> +        public DbSet<MvcMovie.Models.Movie> Movie { get; set; }
setting movies to plural sets the Table name in postgres

2019-05-27 12:13 UTC, truccomarcos requested changes

2019-05-27 12:13 UTC, truccomarcos commented on src/Models/MvcMovieContext.cs
> +        public DbSet<MvcMovie.Models.Movie> Movie { get; set; }
@Casanova569 don't forget to update this. 
`public DbSet<Movie> Movies { get; set; }`
You might need to run another migration afterwards

2019-05-27 12:13 UTC, truccomarcos commented on src/appsettings.json
> +    "MovieContext": "Data Source=MvcMovie.db"
Why is this connection string here?

2019-05-28 19:15 UTC, truccomarcos approved these changes

2019-05-28 19:16 UTC, merged