Repo migra internationalization
wolox-training/jc-net-core pull request #9
Opened 2019-05-23 14:25 UTC by Casanova569

2019-05-23 16:01 UTC, mikolaslorant requested changes

2019-05-23 16:01 UTC, mikolaslorant commented on src/Models/Movie.cs
> +        public decimal Price { get; set; }
you could try adding a Datatype Currency to the price

2019-05-23 16:01 UTC, mikolaslorant commented on src/Models/Movie.cs
> +        public string Title { get; set; }
The title attribute should be [Required]. It doesn't make sense to have a movie without a title

2019-05-23 16:01 UTC, mikolaslorant commented on src/Repositories/Interfaces/IMovieRepository.cs
> +}
add EOF

2019-05-23 16:01 UTC, mikolaslorant commented on src/Repositories/MovieRepository.cs
> +}
Add EOF

2019-05-23 16:01 UTC, mikolaslorant commented on src/Repositories/MovieRepository.cs
> +            return MvcMovieContext.Movies.Include(m => m.Id).SingleOrDefault(m => m.Id == id);
It's not necessary to include the Id. Only models to associated objetcs

2019-05-23 16:01 UTC, mikolaslorant commented on src/Repositories/Repository.cs
> +}
add eof

2019-05-23 16:01 UTC, mikolaslorant commented on .vscode/launch.json
> +}
add eof

2019-05-23 16:01 UTC, mikolaslorant commented on .vscode/tasks.json
> +}
add eof

2019-05-23 16:01 UTC, mikolaslorant commented on src/Models/ErrorViewModel.cs
> +}
add eof

2019-05-23 16:01 UTC, mikolaslorant commented on src/Properties/launchSettings.json
> +}
add eof

2019-05-23 16:01 UTC, mikolaslorant commented on src/Repositories/DataBase/MvcMovieContext.cs
> +}
add eof

2019-05-23 16:01 UTC, mikolaslorant commented on src/Repositories/DataBase/MvcMovieContext.cs
> +        public MvcMovieContext (DbContextOptions<MvcMovieContext> options)
make this three lines just one

2019-05-23 16:01 UTC, mikolaslorant commented on src/Repositories/Interfaces/IRepository.cs
> +}
add eof

2019-05-23 16:01 UTC, mikolaslorant commented on src/Views/HelloWorld/Index.cshtml
> +<p><h1>Hola Mundo</h1></p>
take out header h1 of paragraph p

2019-05-23 16:01 UTC, mikolaslorant commented on src/Views/Home/Privacy.cshtml
> +    <p >@ViewData["Description"]</p>
remove extra space in p

2019-05-23 16:01 UTC, mikolaslorant commented on src/Migrations/20190523142202_InitialMigration.cs
> +                    Title = table.Column<string>(nullable: true),
make title not nullable by make the Title a [Required] Attribute

2019-05-23 16:23 UTC, mikolaslorant commented on src/Models/Movie.cs
> +        public decimal Price { get; set; }
Also the Id of Movie is autogenerated

2019-05-27 12:15 UTC, truccomarcos requested changes
We will need to update this branch since the commit history change between this and the others. Remind to see this once the previous ones are merged

2019-05-29 13:56 UTC, truccomarcos requested changes
On the Privacy view, you are using the localizer directly on the view setting the `ViewData["Title"]` and `ViewData["Description"]` values. But the controller is setting a `ViewData["Message"]`, that is not being used anywhere.

Try localizing the `Home` view using only controller localized strings, and the `Privacy` view using only view localized strings

I also had some trouble running the migrations. I believe there was a similar issue on another branch, but since we have migrations on this one, it makes sense that they work here. Please take a look at that error as well (try using another database name on your connection string to avoid losing the current progress)

2019-05-29 13:56 UTC, truccomarcos commented on src/appsettings.Development.json
> +{
This file shouldn't be here (didn't you add it to the .gitignore file?)

2019-05-29 13:56 UTC, truccomarcos commented on src/Controllers/HomeController.cs
> +            ViewData["Message"] = _localizer["PrivacyPage"];
try using a property to access `private readonly` attributes.
You should be able to click on it, open the quickfix menu on vscode (click on💡 or `ctrl+.`) and select the `Encapsulate field` option.

You should get something like this>
```csharp
public IHtmlLocalizer<HomeController> Localizer => this._localizer;
```

2019-05-29 13:56 UTC, truccomarcos commented on src/Startup.cs
> +            //CultureInfo.CurrentCulture = new CultureInfo("fr-FR");
remove this comment

2019-05-29 13:56 UTC, truccomarcos commented on src/Repositories/Interfaces/IMovieRepository.cs
> +namespace Queries.Core.Repositories
Update this namespace so that it follows the folder structure
`MvcMovie.Repositories.Interfaces`

2019-05-29 13:56 UTC, truccomarcos commented on src/Repositories/Interfaces/IRepository.cs
> +namespace Queries.Core.Repositories
Update this namespace

2019-05-29 13:56 UTC, truccomarcos commented on src/Repositories/Interfaces/IUnitOfWork.cs
> +namespace Queries.Core
Update Namespace

2019-05-29 13:56 UTC, truccomarcos commented on src/Repositories/MovieRepository.cs
> +namespace Queries.Persistence.Repositories
Update namespace

2019-05-29 13:56 UTC, truccomarcos commented on src/Repositories/Repository.cs
> +namespace Queries.Persistence.Repositories
Update Namespace

2019-05-29 13:56 UTC, truccomarcos commented on src/Controllers/HelloWorld.cs
>  namespace src.Controllers
Update the namespace to `MvcMovie.Controllers`

2019-05-29 13:57 UTC, truccomarcos commented
Don't forget to reassing the PR to us once the corrections are done

2019-06-03 14:59 UTC, truccomarcos commented on src/Migrations/20190523142202_InitialMigration.cs
> +                    Title = table.Column<string>(nullable: true),
Because you made the Title attribute `[Required]`, you will need to run another migration here. You will need to be careful though, running the migration again now might break migrations on later PRs.

2019-06-03 15:16 UTC, truccomarcos approved these changes

2019-06-04 14:57 UTC, merged